In [175]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [158]:
file=r"C:\Users\Akshaya\OneDrive\Desktop\Internship\Task3\heart.csv"
df=pd.read_csv(file)

In [159]:
df.shape

(1025, 14)

In [160]:
print(df.columns.tolist())

['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']


In [161]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [162]:
df.duplicated().sum()

np.int64(723)

In [163]:
df=df.drop_duplicates()

In [164]:
df.shape

(302, 14)

In [165]:
x=df.drop('target', axis=1)
y=df['target']

In [166]:
scal=StandardScaler()
x_scal=scal.fit_transform(x)

In [167]:
x_train, x_test, y_train, y_test= train_test_split(x_scal, y, test_size=0.2, random_state=45)

In [170]:
mod=RandomForestClassifier(random_state=42)
mod.fit(x_train, y_train)
y_pred=mod.predict(x_test)
print("Random Forest")
print("Accuracy", accuracy_score(y_test, y_pred))
print("Confusion Matrix\n", confusion_matrix(y_test, y_pred))
print("Classification Matrix\n", classification_report(y_test, y_pred))

Random Forest
Accuracy 0.8032786885245902
Confusion Matrix
 [[23  9]
 [ 3 26]]
Classification Matrix
               precision    recall  f1-score   support

           0       0.88      0.72      0.79        32
           1       0.74      0.90      0.81        29

    accuracy                           0.80        61
   macro avg       0.81      0.81      0.80        61
weighted avg       0.82      0.80      0.80        61



In [ ]:
model = HistGradientBoostingClassifier(random_state=42)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

print("Hist Gradradient")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix\n", confusion_matrix(y_test, y_pred))
print("Classification Matrix\n", classification_report(y_test, y_pred))

Hist Gradradient
Accuracy: 0.7540983606557377
Confusion Matrix
 [[22 10]
 [ 5 24]]
Classification Matrix
               precision    recall  f1-score   support

           0       0.81      0.69      0.75        32
           1       0.71      0.83      0.76        29

    accuracy                           0.75        61
   macro avg       0.76      0.76      0.75        61
weighted avg       0.76      0.75      0.75        61



In [ ]:
voting_model = VotingClassifier(estimators=[
    ('lr', LogisticRegression(max_iter=1000)),
    ('rf', RandomForestClassifier()),
    ('svc', SVC(probability=True))
], voting='soft')

voting_model.fit(x_train, y_train)
y_pred = voting_model.predict(x_test)
print("Ensambling")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix\n", confusion_matrix(y_test, y_pred))
print("Classification Matrix\n", classification_report(y_test, y_pred))

Ensambling
Accuracy: 0.819672131147541
Confusion Matrix
 [[21 11]
 [ 0 29]]
Classification Matrix
               precision    recall  f1-score   support

           0       1.00      0.66      0.79        32
           1       0.72      1.00      0.84        29

    accuracy                           0.82        61
   macro avg       0.86      0.83      0.82        61
weighted avg       0.87      0.82      0.82        61



In [172]:
svc_model = SVC(kernel='rbf', probability=True)
svc_model.fit(x_train, y_train)
svc_pred = svc_model.predict(x_test)
print("SVC\nAccuracy:", accuracy_score(y_test, svc_pred))
print("Confusion Matrix\n", confusion_matrix(y_test, y_pred))
print("Classification Matrix\n", classification_report(y_test, y_pred))

SVC
Accuracy: 0.8032786885245902
Confusion Matrix
 [[21 11]
 [ 0 29]]
Classification Matrix
               precision    recall  f1-score   support

           0       1.00      0.66      0.79        32
           1       0.72      1.00      0.84        29

    accuracy                           0.82        61
   macro avg       0.86      0.83      0.82        61
weighted avg       0.87      0.82      0.82        61



In [173]:
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train, y_train)
knn_pred = knn_model.predict(x_test)
print("KNN\nAccuracy:", accuracy_score(y_test, knn_pred))
print("Confusion Matrix\n", confusion_matrix(y_test, y_pred))
print("Classification Matrix\n", classification_report(y_test, y_pred))

KNN
Accuracy: 0.8524590163934426
Confusion Matrix
 [[21 11]
 [ 0 29]]
Classification Matrix
               precision    recall  f1-score   support

           0       1.00      0.66      0.79        32
           1       0.72      1.00      0.84        29

    accuracy                           0.82        61
   macro avg       0.86      0.83      0.82        61
weighted avg       0.87      0.82      0.82        61



In [174]:
nb_model = GaussianNB()
nb_model.fit(x_train, y_train)
nb_pred = nb_model.predict(x_test)
print("Naive Bayes\nAccuracy:", accuracy_score(y_test, nb_pred))
print("Confusion Matrix\n", confusion_matrix(y_test, y_pred))
print("Classification Matrix\n", classification_report(y_test, y_pred))

Naive Bayes
Accuracy: 0.8360655737704918
Confusion Matrix
 [[21 11]
 [ 0 29]]
Classification Matrix
               precision    recall  f1-score   support

           0       1.00      0.66      0.79        32
           1       0.72      1.00      0.84        29

    accuracy                           0.82        61
   macro avg       0.86      0.83      0.82        61
weighted avg       0.87      0.82      0.82        61



In [177]:
import joblib
joblib.dump(knn_model, "knn_model.pkl")
joblib.dump(scal, "scaler.pkl")
print("✅ Model and scaler saved successfully.")

✅ Model and scaler saved successfully.
